Repository UKHO/exchange-set-fulfilment-service, pull requests merged in 2025-08, with the labels that each got.

#102 232455 To generate error.txt when EFS fails
  config/configuration.json
  src/UKHO.ADDS.EFS.Builder.Common/UKHO.ADDS.EFS.Builder.Common.csproj
  src/UKHO.ADDS.EFS.Builder.S100/Pipelines/Distribute/UploadFilesNode.cs
  src/UKHO.ADDS.EFS.Domain/Constants/ApiHeaderKeys.cs
  src/UKHO.ADDS.EFS.Domain/UKHO.ADDS.EFS.Domain.csproj
  src/UKHO.ADDS.EFS.Domain/Utilities/FileNameGenerator.cs
  src/UKHO.ADDS.EFS.Orchestrator/Infrastructure/Logging/OrchestratorLogs.cs
  src/UKHO.ADDS.EFS.Orchestrator/Pipelines/Assembly/Nodes/S100/GetS100ProductNamesNode.cs
  src/UKHO.ADDS.EFS.Orchestrator/Pipelines/Completion/Nodes/S100/CommitFileShareBatchNode.cs
  src/UKHO.ADDS.EFS.Orchestrator/Pipelines/Completion/Nodes/S100/CreateErrorFileNode.cs
  src/UKHO.ADDS.EFS.Orchestrator/Pipelines/Completion/S100CompletionPipeline.cs
  src/UKHO.ADDS.EFS.Orchestrator/Pipelines/Infrastructure/PipelineContext.cs
  src/UKHO.ADDS.EFS.Orchestrator/Services/Infrastructure/IOrchestratorFileShareClient.cs
  src/UKHO.ADDS.EFS.Orchestrator/Services/Infrastructure/OrchestratorFileShareClient.cs
  test/UKHO.ADDS.EFS.Domain.UnitTests/Utilities/FileNameGeneratorTests.cs
  test/UKHO.ADDS.EFS.Orchestrator.UnitTests/Pipelines/Completion/Nodes/S100/CreateErrorFileNodeTests.cs
  test/UKHO.ADDS.EFS.Orchestrator.UnitTests/Services/FileShareServiceTest.cs
Labels: Prayag

#101 235435 Implement concurrent file download with locking
  src/UKHO.ADDS.EFS.Builder.S100/Pipelines/Assemble/DownloadFilesNode.cs
Labels: bug

#109 234651 - Filter on product specifications
  EFS.sln
  src/UKHO.ADDS.EFS.Builder.S100/Pipelines/Create/AddContentExchangeSetNode.cs
  test/UKHO.ADDS.EFS.Builder.S100.UnitTests/Pipeline/Create/AddContentExchangeSetNodeTest.cs
  test/UKHO.ADDS.EFS.EndToEndTests/EndToEndTests.cs
  test/UKHO.ADDS.EFS.EndToEndTests/TestData/exchangeSet-25Products.testzip
  test/UKHO.ADDS.EFS.EndToEndTests/UKHO.ADDS.EFS.EndToEndTests.csproj
  test/UKHO.ADDS.EFS.FunctionalTests/FunctionalTests.cs
  test/UKHO.ADDS.EFS.FunctionalTests/Services/OrchestratorCommands.cs
  test/UKHO.ADDS.EFS.FunctionalTests/Services/TestBase.cs
  test/UKHO.ADDS.EFS.FunctionalTests/Services/ZipStructureComparer.cs
  test/UKHO.ADDS.EFS.FunctionalTests/TestData/AllProducts.zip
  test/UKHO.ADDS.EFS.FunctionalTests/TestData/MultipleProducts.zip
  test/UKHO.ADDS.EFS.FunctionalTests/TestData/Single101Product.zip
  test/UKHO.ADDS.EFS.FunctionalTests/TestData/Single102Product.zip
  test/UKHO.ADDS.EFS.FunctionalTests/TestData/Single104Product.zip
  test/UKHO.ADDS.EFS.FunctionalTests/TestData/Single111Product.zip
  test/UKHO.ADDS.EFS.FunctionalTests/TestData/SingleProductAndStartWithS104Products.zip
  test/UKHO.ADDS.EFS.FunctionalTests/TestData/StartWithS101AndS111.zip
  test/UKHO.ADDS.EFS.FunctionalTests/TestData/StartWithS101Products.zip
  test/UKHO.ADDS.EFS.FunctionalTests/TestData/StartWithS102Products.zip
  test/UKHO.ADDS.EFS.FunctionalTests/TestData/StartWithS104Products.zip
  test/UKHO.ADDS.EFS.FunctionalTests/TestData/StartWithS111Products.zip
  test/UKHO.ADDS.EFS.FunctionalTests/TestData/WithoutFilter.zip
  test/UKHO.ADDS.EFS.FunctionalTests/UKHO.ADDS.EFS.FunctionalTests.csproj
  test/UKHO.ADDS.EFS.Orchestrator.UnitTests/Pipelines/Assembly/Nodes/S100/FilterProductsNodeTest.cs
Labels: Agastya

#114 Dev/234316 create background task to call job api
  configuration/configuration.json
  src/UKHO.ADDS.EFS.Orchestrator/Api/JobsApiRouteBuilderExtension.cs
  src/UKHO.ADDS.EFS.Orchestrator/Infrastructure/Logging/OrchestratorLogs.cs
  src/UKHO.ADDS.EFS.Orchestrator/InjectionExtensions.cs
  src/UKHO.ADDS.EFS.Orchestrator/Pipelines/Infrastructure/Assembly/AssemblyPipeline.cs
  src/UKHO.ADDS.EFS.Orchestrator/Pipelines/Infrastructure/Assembly/AssemblyPipelineFactory.cs
  src/UKHO.ADDS.EFS.Orchestrator/Pipelines/Infrastructure/Assembly/IAssemblyPipeline.cs
  src/UKHO.ADDS.EFS.Orchestrator/Pipelines/Infrastructure/Assembly/IAssemblyPipelineFactory.cs
  src/UKHO.ADDS.EFS.Orchestrator/Schedule/SchedulerJob.cs
  src/UKHO.ADDS.EFS.Orchestrator/UKHO.ADDS.EFS.Orchestrator.csproj
  test/UKHO.ADDS.EFS.Orchestrator.UnitTests/Schedule/SchedulerJobTests.cs
Labels: Agastya

#105 228184 logging integration
  src/UKHO.ADDS.EFS.Aspire/Services/HostApplicationBuilderExtensions.cs
  src/UKHO.ADDS.EFS.Aspire/UKHO.ADDS.EFS.Aspire.csproj
  src/UKHO.ADDS.EFS.Domain/Configuration/Namespaces/ServiceConfiguration.cs
  src/UKHO.ADDS.EFS.LocalHost/Program.cs
  src/UKHO.ADDS.EFS.LocalHost/Regenerating infra.md
  src/UKHO.ADDS.EFS.LocalHost/UKHO.ADDS.EFS.LocalHost.csproj
  src/UKHO.ADDS.EFS.LocalHost/infra/efs-app-insights/efs-app-insights.module.bicep
  src/UKHO.ADDS.EFS.LocalHost/infra/efs-events-namespace/efs-events-namespace.module.bicep
  src/UKHO.ADDS.EFS.LocalHost/infra/efs-orchestrator-roles-efs-events-namespace/efs-orchestrator-roles-efs-events-namespace.module.bicep
  src/UKHO.ADDS.EFS.LocalHost/infra/efs-orchestrator/efs-orchestrator.module.bicep
  src/UKHO.ADDS.EFS.LocalHost/infra/efs-orchestrator/efs-orchestrator.tmpl.bicepparam
  src/UKHO.ADDS.EFS.LocalHost/infra/main.bicep
  src/UKHO.ADDS.EFS.Orchestrator/Infrastructure/Logging/Implementation/EventHubSerilogSink.cs
  src/UKHO.ADDS.EFS.Orchestrator/Pipelines/Assembly/Nodes/S100/GetS100ProductNamesNode.cs
  src/UKHO.ADDS.EFS.Orchestrator/Program.cs
  src/UKHO.ADDS.EFS.Orchestrator/UKHO.ADDS.EFS.Orchestrator.csproj
Labels: Prayag

#124 Dev/235478 handle all invalid products in scs mock
  mock/UKHO.ADDS.Mocks.EFS/Override/Mocks/scs/ProductNamesEndpoint.cs
  mock/UKHO.ADDS.Mocks.EFS/Override/Mocks/scs/ResponseGenerator/ScsResponseGenerator.cs
  mock/UKHO.ADDS.Mocks.EFS/Program.cs
  src/UKHO.ADDS.EFS.Orchestrator/Pipelines/Assembly/Nodes/S100/GetS100ProductNamesNode.cs
Labels: Agastya
